apiVersion: v2
name: k8s-viewer
description: k8s-viewer Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: v0.1.0
kubeVersion: ">= 1.21.0-0"
home: https://github.com/oruharo/k8s-demo
# icon: https://raw.githubusercontent.com/oruharo/k8s-demo/main/logo/logo.png
sources:
  - https://github.com/oruharo/k8s-demo
annotations:
  artifacthub.io/prerelease: "false"
maintainers:
  - name: oruharo
    url: https://github.com/oruharo
    email: oruharo@github.com
keywords:
  - kubernetes
  - codespaces
  - dev-environment
  - dev-container
