apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "k8s-viewer.labels" . | nindent 4 }}
  name: k8s-viewer
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: k8s-viewer
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    {{- include "k8s-viewer.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "k8s-viewer.labels" . | nindent 4 }}
  name: k8s-viewer
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-viewer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-viewer.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - args:
        # - --zap-log-level={{ .Values.logLevel }}
        # - --zap-time-encoding={{ .Values.logTimeEncoding }}
        # {{- if ne .Values.logLevel "info" }}
        # - --zap-devel=true
        # {{- end }}
        command:
        - /app/k8s-viewer-sv
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /
            port: 6000
          initialDelaySeconds: 3
          periodSeconds: 3
        name: k8s-viewer
        ports:
        - containerPort: 6000
          name: https
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        {{- if not .Values.insecure }}
        volumeMounts:
        - mountPath: /app/cert
          name: cert
          readOnly: true
        {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "k8s-viewer.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- if not .Values.insecure }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ .Values.cert.secretName }}
      {{- end }}
